apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
        release: "{{ .Release.Name }}"
    spec:
      securityContext:
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
      containers:
      - name: "{{ .Chart.Name }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        {{- with .Values.config }}
        {{- if .publicAddress }}
          - name: PUBLIC_ADDRESS
            value: {{ .publicAddress | squote}}
        {{- end }}
        {{- if .bindAddress }}
          - name: BIND_ADDRESS
            value: {{ .bindAddress | squote }}
        {{- end }}
        {{- if .gamePort }}
          - name: GAME_PORT
            value: {{ .gamePort | squote }}
        {{- end }}
        {{- if .rconPort }}
          - name: RCON_PORT
            value: {{ .rconPort | squote }}
        {{- end }}
        {{- if .rconPassword }}
          - name: RCON_PASSWORD
            value: {{ .rconPassword | squote }}
        {{- end }}
        {{- if .rconAddress }}
          - name: RCON_ADDRESS
            value: {{ .rconAddress | squote }}
        {{- end }}
        {{- if .rconBlacklist }}
          - name: RCON_BLACKLIST
            value: {{ .rconBlacklist | squote }}
        {{- end }}
        {{- if .rconWhitelist }}
          - name: RCON_WHITELIST
            value: {{ .rconWhitelist | squote }}
        {{- end }}
        {{- if .a2sPort }}
          - name: A2S_PORT
            value: {{ .a2sPort | squote }}
        {{- end }}
        {{- if .serverConfigFile }}
          - name: SERVER_CONFIG_FILE
            value: {{ .serverConfigFile | squote }}
        {{- end }}
        {{- if .maxFps }}
          - name: MAX_FPS
            value: {{ .maxFps | squote }}
        {{- end }}
        {{- if .maxPlayers }}
          - name: MAX_PLAYERS
            value: {{ .maxPlayers | squote }}
        {{- end }}
        {{- if .serverName }}
          - name: SERVER_NAME
            value: {{ .serverName | squote }}
        {{- end }}
        {{- if .serverPassword }}
          - name: SERVER_PASSWORD
            value: {{ .serverPassword | squote }}
        {{- end }}
        {{- if .admins }}
          - name: ADMINS
            value: {{ .admins | squote }}
        {{- end }}
        {{- if .adminPassword }}
          - name: ADMIN_PASSWORD
            value: {{ .adminPassword | squote }}
        {{- end }}
        {{- if .scenarioId }}
          - name: SCENARIO_ID
            value: {{ .scenarioId | squote }}
        {{- end }}
        {{- if .visible }}
          - name: VISIBLE
            value: {{ .visible | squote}}
        {{- end }}
        {{- if .crossplatform }}
          - name: CROSSPLATFORM
            value: {{ .crossplatform | squote }}
        {{- end }}
        {{- if .supportedPlatforms }}
          - name: SUPPORTED_PLATFORMS
            value: {{ .supportedPlatforms | squote }}
        {{- end }}
        {{- if .serverMaxViewDistance }}
          - name: SERVER_MAX_VIEW_DISTANCE
            value: {{ .serverMaxViewDistance | squote }}
        {{- end }}
        {{- if .networkViewDistance }}
          - name: NETWORK_VIEW_DISTANCE
            value: {{ .networkViewDistance | squote }}
        {{- end }}
        {{- if .disableThirdPerson }}
          - name: DISABLE_THIRD_PERSON
            value: {{ .disableThirdPerson | squote}}
        {{- end }}
        {{- if .fastValidation }}
          - name: FAST_VALIDATION
            value: {{ .fastValidation | squote }}
        {{- end }}
        {{- if .battleye }}
          - name: BATTLEYE
            value: {{ .battleye | squote }}
        {{- end }}
        {{- if .modsJsonB64 }}
          - name: MODS_JSON_B64
            value: {{ .modsJsonB64 | squote}}
        {{- end }}
        {{- if .queueMaxSize }}
          - name: QUEUE_MAX_SIZE
            value: {{ .queueMaxSize | squote}}
        {{- end }}
        {{- if .additionalParameters }}
          - name: ADDITIONAL_PARAMETERS
            value: {{ .additionalParameters | squote }}
        {{- end }}
        {{- end }}
        ports:
        - name: game
          containerPort: {{ .Values.config.gamePort | int }}
          protocol: UDP
        - name: rcon
          containerPort: {{ .Values.config.rconPort | int }}
          protocol: TCP
        - name: a2s
          containerPort: {{ .Values.config.a2sPort | int }}
          protocol: UDP
        volumeMounts:
        - name: data
          mountPath: /home/steam/reforger
        securityContext:
          allowPrivilegeEscalation: false
          
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: "{{ .Chart.Name }}-data"
